### ISSUE TITLE
Need to be able to set a delay for the video, regardless of photo

### ISSUE THREAD

**Issue by mrepik** [marijnkampf/Random-Photo-Screensaver#94] opened 2017-07-26 19:29 UTC
For photo delay 10-20sec normaly, but for video need minimum 60-120sec. thanx

**Comment by marijnkampf** [comment] 2017-07-26 20:58
Duplicate of https://github.com/marijnkampf/Random-Photo-Screensaver/issues/40

**Closed by marijnkampf** 2017-07-26 20:58 UTC
