### ISSUE TITLE
add automatic crash log sending

### ISSUE THREAD

**Issue by mailinglists35** [marijnkampf/Random-Photo-Screensaver#63] opened 2016-03-29 01:22 UTC
i'm quite tired of sending bug reports.  a debug version would be very useful so I can only type in additional comments and hit the send button.

 for example right now it's crashing when I click the preview button in windows screensaver and this is for me such a basic thing that i'm really feeling I make a great effort to collect all that info myself - i mean this bug should really not be present not even in a beta quality release.

**Comment by marijnkampf** [comment] 2016-03-29 16:41
Unfortunately without error details, the RPS version and OS details there is nothing I can do to fix it, as it works fine on my test systems.

**Comment by marijnkampf** [comment] 2016-03-29 17:40
Duplicate of issue #49.

**Closed by marijnkampf** 2016-03-29 17:40 UTC
Labels: duplicate, enhancement
